config/routes.rb
Site::Application.routes.draw do
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  
  root :to => 'static_pages#home'
  
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy', :via => :delete
    

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer         not null, primary key
#  firstname       :string(255)
#  email           :string(255)
#  created_at      :datetime        not null
#  updated_at      :datetime        not null
#  password_digest :string(255)
#  lastname        :string(255)
#  date_of_birth   :date
#  nickname        :string(255)
#  gender          :string(255)
#

class User < ActiveRecord::Base
  attr_accessible :email, :firstname, :password
  
  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token
  
  validates :firstname,:presence => true, :length => { :maximum => 100 }
  
  has_secure_password
  
  validates :password, :length => {:minimum => 6,:message => "debe tener como mínimo 6 caracteres"}
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, :format => { :with => VALID_EMAIL_REGEX },:uniqueness => { :case_sensitive => false }
  
  private

    def create_remember_token
      self.remember_token = SecureRandom.hex
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def create
	  
	  user = User.find_by_email(params[:session][:email])
	  if user && user.authenticate(params[:session][:password])
	    flash[:success] = 'Qué alegría tenerte de nuevo ' + user.firstname
	    sign_in user
	    redirect_to user
	  else
	    flash.now[:error] = 'Mmmmh, le pifiaste en algo'
	    render 'new'
	  end
	  
	end
	
	def destroy
	  sign_out
      redirect_to root_path
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	@user = User.new
  	render :layout => 'prelogin'
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
  	@user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:success] = "Bienvenido a cheLibro " + @user.firstname
      sign_in @user
      
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper


end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end
  
  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end
	
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://localhost:3000/"></a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Acerca de",   '#' %></li>
      <li><%= link_to "Contacto", '#' %></li>
      <li><a href="http://localhost:3000/">Novedades</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "sample app", root_path, :id => "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", root_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", '#' %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", '#' %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, :method => "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_prelogin_header.html.erb
<header class="navbar navbar-fixed-top">
	<div>
		<div class="container">
		  <nav>
		    <ul id="navigation" class="nav">
				<li id="key"><%= link_to image_tag("key.png", :border=>0), '#', 
						:onclick => "showForm()",
						:rel => 'tooltip', 
						:title => 'Iniciar sesión'						
					%>
				</li>
				<li><%= link_to image_tag("home.png", :border=>0), '#', :rel => 'tooltip', :title => 'Inicio' %></li>
				<li><%= link_to image_tag("lists.png", :border=>0), '#', :rel => 'tooltip', :title => 'Listas' %></li>
				<li><%= link_to image_tag("explore.png", :border=>0), '#', :rel => 'tooltip', :title => 'Explorar' %></li>
		    </ul>
		  </nav>
		  
		</div>
	</div>
	
	<%= render 'prelogin/forms' %> 	
</header>

<script type="text/javascript">
	$(document).ready(function(){
		$('#navigation').tooltip({
			selector: "a[rel=tooltip]",
			placement: "bottom"
		});
		$('#key').tooltip({
			selector: "a[rel=tooltip]",
			placement: "left"
		});
	});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title> chelibro </title>
	<%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
</head>
<body>

	<%= render 'layouts/header' %>
    
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      
      <%= yield %>
      
      <%= render 'layouts/footer' %>
      
      <%= debug(params) if Rails.env.development? %>
    </div>
    

</body>
</html>

app/views/layouts/prelogin.html.erb
<!DOCTYPE html>
<html lang="es">
<head>
	<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
	<title> Imaginario </title>
	<%= stylesheet_link_tag "prelogin" %>
	<%= javascript_include_tag "application" %>
	<%= javascript_include_tag "prelogin" %>
	<%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/prelogin_header' %>
		
	<div id="wrapper"> 
		<div class="container">
			<%= yield %>
		</div>
		<%= debug(params) if Rails.env.development? %>
	</div>
	
</body>
</html>

app/views/prelogin/_forms.html.erb
<div id="signin_signout" class="row span3 well">
	<div id="signin">
		<h4> Inicio de sesión </h4>
		<%= link_to "Soy nuevo","#", 'class' => 'change', :class => "newUser", :onclick => "showSignup()" %>
		<div class="row">
			<div class="span3">
				<%= form_for(:session, :url => sessions_path) do |f| %>
				
					<%= f.text_field :email, :placeholder => 'Correo' %>
					<%= f.password_field :password, :placeholder => 'Clave' %>
										
					<%= f.submit "Iniciar sesión", :class => "btn btn-primary" %>
					<%= link_to "Olvidé mi clave","#", :class => 'forgot' %>
					
				<% end %>
				
				
			</div>
		</div>
		
	</div>
	
	<div id="signup">
		<h4> Registro de usuario </h4>
		<div class="row">
			<div class="span3">
				<%= form_for(@user) do |f| %>
				
					<%= f.text_field :firstname, :placeholder => 'Nombre' %>
					
					<%= f.text_field :email, :placeholder => 'Correo' %>
					
					<%= f.password_field :password, :placeholder => 'Clave' %>
					
					<%= f.submit "Registrarme", :class => "btn btn-primary" %>
					
					<%= link_to "Soy usuario","#", 'class' => 'imUser', :onclick => "showSignin()" %>
					
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li> <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<div id="search">
	<%= image_tag("logo.png",:id => 'logo', :alt => 'Imaginario') %>

	<form id="searchForm" class="form-search">
		<input id="searchBox" type="text" class="input-large" placeholder="Autor / Título / ISBN">
	</form>
</div>

<footer> 
	<%= image_tag("pajarito.png") %> 
	<p class="lead">
		Oye chabal! Si no sabes qué libro leer, quieres saber qué están leyendo tus amiguicos o quizás recomendarle un librico a tu amorsico has iegado al lugar indicado. Además, si quieres mantener toda tu biblioteca de forma virtual puedes hacerlo registrandote en IMAGINARIO. TQM  
	</p>
</footer>

app/views/users/new.html.erb
<h1> Registro de usuario </h1>
<div class="row">
  <div class="span6 offset3">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages' %>
		
			<%= f.text_field :firstname, :placeholder => 'Nombre' %>
			
			<%= f.text_field :email, :placeholder => 'Correo' %>
			
			<%= f.password_field :password, :placeholder => 'Clave' %>
			
			<%= f.submit "Registrarme", :class => "btn btn-primary" %>
			
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<%= "Hola " + @user.firstname %>, <%= @user.email %>